### PR TITLE
Bump Elasticsearch spark version to 8.2.3

### LINKED ISSUE #125: Support for Elasticsearch 8.x
**Describe the bug**

Today Spark dependencies only work with elasticsearch 7.x

**To Reproduce**
1.  install elasticsearch 8.x
2. launch spark dependencies
3.

we have this in logs:

```
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
        at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:348)
        at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:220)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:79)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:78)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:48)
        at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:273)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
        at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:273)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:269)
        at org.apache.spark.Partitioner$.$anonfun$defaultPartitioner$4(Partitioner.scala:78)
        at org.apache.spark.Partitioner$.$anonfun$defaultPartitioner$4$adapted(Partitioner.scala:78)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.immutable.List.map(List.scala:298)
        at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:78)
        at org.apache.spark.rdd.RDD.$anonfun$groupBy$1(RDD.scala:714)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
        at org.apache.spark.rdd.RDD.groupBy(RDD.scala:714)
        at org.apache.spark.api.java.JavaRDDLike.groupBy(JavaRDDLike.scala:243)
        at org.apache.spark.api.java.JavaRDDLike.groupBy$(JavaRDDLike.scala:239)
        at org.apache.spark.api.java.AbstractJavaRDDLike.groupBy(JavaRDDLike.scala:45)
        at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:273)
        at io.jaegertracing.spark.dependencies.elastic.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:249)
        at io.jaegertracing.spark.dependencies.DependenciesSparkJob.run(DependenciesSparkJob.java:54)
        at io.jaegertracing.spark.dependencies.DependenciesSparkJob.main(DependenciesSparkJob.java:40)
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Unsupported/Unknown Elasticsearch version [8.2.3].Highest supported version is [7.x]. You may need to upgrade ES-Hadoop.
        at org.elasticsearch.hadoop.util.EsMajorVersion.parse(EsMajorVersion.java:91)
        at org.elasticsearch.hadoop.rest.RestClient.mainInfo(RestClient.java:756)
        at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:338)
        ... 31 more
```

**Expected behavior**
It would be nice to make it work with ES 8.x (Jaeger is "supporting" it)

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.31
 - Deployment: Kubernetes

**Additional context**

maybe by using this in pom.xml:

```xml
<dependency>
    <groupId>org.elasticsearch</groupId>
    <artifactId>elasticsearch-spark-20_${version.scala.binary}</artifactId>
    <version>8.2.3</version>
</dependency>
```

### PR DESCRIPTION
**Pull request by sylvainOL**
Current version of elasticsearch-spark-20 jar is using a 7.x version and doesn't want to work with Elasticsearch 8.x.

## Which problem is this PR solving?
- Resolves #125

## Short description of the changes
- Bumping version of jar to make it also work with 8.x versions.

### CODE REVIEW

**Comment by pavolloffay** [comment]
> and doesn't want to work with Elasticsearch 8.x.

If this issue is resolving ES8 compatibility then there should be e2e test for ES 8 e.g. https://github.com/jaegertracing/spark-dependencies/blob/main/.github/workflows/ci.yaml#L25

**Comment by sylvainOL** [comment]
I've added a test for es8.

But I'm not sure at all it'll work with es `5.6.9` which is the default version...

**Comment by pavolloffay** [comment]
> But I'm not sure at all it'll work with es 5.6.9 which is the default version...

We should find out. Are you using Jaeger with ES8 https://github.com/jaegertracing/jaeger/issues/3571?

**Comment by s7an-it** [comment]
@sylvainOL, what is the state of this change, can we say prod backend ES is ok after this if you run it?

**Comment by sergiomcalzada** [comment]
Any update on this?

**Comment by sylvainOL** [comment]
Hello,
it doesn't seems to work sorry :(

**Comment by desert3agle** [comment]
does spark jobs work with opensearch?

**Comment by piratetm** [comment]
up

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
