### PR TITLE
Enables client authentication on cassandra SSL connections

### PR DESCRIPTION
**Pull request by narayanasamyr**
## Which problem is this PR solving?
-

## Short description of the changes
-

### CODE REVIEW

**Comment by pavolloffay** [comment]
Hi @narayanasamyr did you try setting `javax.net.ssl.*` options to `JAVA_OPTS`? https://github.com/jaegertracing/spark-dependencies/pull/26/files#diff-04c6e90faac2675aa89e2176d2eec7d8R21

**Comment by narayanasamyr** [comment]
> Hi @narayanasamyr did you try setting `javax.net.ssl.*` options to `JAVA_OPTS`? https://github.com/jaegertracing/spark-dependencies/pull/26/files#diff-04c6e90faac2675aa89e2176d2eec7d8R21

Hi,
Yes i have tried that, but it didn't work.

prblm is as per this doc https://github.com/datastax/spark-cassandra-connector/blob/master/doc/reference.md#cassandra-ssl-connection-options we need to set below properties to enable the client auth and those are not populated through  `javax.net.ssl.*` 

connection.ssl.clientAuth.enabled
connection.ssl.keyStore.password
connection.ssl.keyStore.path

**Comment by pavolloffay** [comment]
thanks @narayanasamyr

**Comment by rbtcollins** [comment]
Thanks @narayanasamyr  & @pavolloffay - to explain further - this is what i had in my prior PR, and we only just finally got back to reviewing what was merged vs what we needed to have it work with unmodified upstream builds.

**Pull request merged**
